# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Sankaran
tagline:          'A website'
description:      'I make stuff'
url:              https://sankaranv.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Sankaran Vaidyanathan'
  url:            https://twitter.com/sankaranv8

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
#version:            0.1 (beta)
sidebar_home_link:  true
github:
  repo:             https://github.com/sankaranv
disqus:
  shortname: sankaranv
