# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Sankaran Vaidyanathan
tagline:          'Personal Webpage'
description:      'sankaranv[at]cs.umass.edu'
url:              https://sankaranv.github.io
#baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Sankaran Vaidyanathan'
  url:            https://sankaranv.github.io

paginate:         5
paginate_path:    '/blog/page:num'
#                     Or '/blog/page:num' if you want to move your index pages


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

email:              sankaranv@cs.umass.edu
scholar:            https://scholar.google.com/citations?user=DbeHYRcAAAAJ&hl=en
github:
  repo:             https://github.com/sankaranv
twitter:            https://twitter.com/sankaranv8
linkedin:           https://www.linkedin.com/in/sankaranv8/

collections:
  posts:
    output: true
    permalink: /blog/:title


# Include all files under '_pages' as files in root directory
include: ['_pages']

# Sidebar link settings
sidebar_home_link:  true
sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
sidebar_about_link: '/index.html'