name: Build and Deploy al-folio to gh-pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Install Jupyter
        run: pip install jupyter

      - name: Build the site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Clone and push to gh-pages branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git clone --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          rm -rf gh-pages/*
          cp -r _site/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git add .
          git commit -m "Update site on $(date)"
          git push origin gh-pages
