name: Build and Deploy al-folio to gh-pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Deploy to gh-pages
        run: |
          cd _site
          touch .nojekyll  # disable GitHub's Jekyll processing
          git init
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git commit -m "Deploy site from master branch"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:gh-pages
